//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status change.
        /// </summary>
        public static string AccountStatusChange {
            get {
                return ResourceManager.GetString("AccountStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status change message.
        /// </summary>
        public static string AccountStatusChangeMessage {
            get {
                return ResourceManager.GetString("AccountStatusChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status was changed.
        /// </summary>
        public static string AccountStatusWasChanged {
            get {
                return ResourceManager.GetString("AccountStatusWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a card.
        /// </summary>
        public static string AddACard {
            get {
                return ResourceManager.GetString("AddACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add author.
        /// </summary>
        public static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card for member.
        /// </summary>
        public static string AddCardForMember {
            get {
                return ResourceManager.GetString("AddCardForMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete rack.
        /// </summary>
        public static string AreYouSureYouWantToDeleteRack {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to menu.
        /// </summary>
        public static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block a card.
        /// </summary>
        public static string BlockACard {
            get {
                return ResourceManager.GetString("BlockACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block card.
        /// </summary>
        public static string BlockCard {
            get {
                return ResourceManager.GetString("BlockCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book ISBN.
        /// </summary>
        public static string BookISBN {
            get {
                return ResourceManager.GetString("BookISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book item.
        /// </summary>
        public static string BookItem {
            get {
                return ResourceManager.GetString("BookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book item details.
        /// </summary>
        public static string BookItemDetails {
            get {
                return ResourceManager.GetString("BookItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book item ISBN.
        /// </summary>
        public static string BookItemISBN {
            get {
                return ResourceManager.GetString("BookItemISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book items.
        /// </summary>
        public static string BookItems {
            get {
                return ResourceManager.GetString("BookItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is loaned until.
        /// </summary>
        public static string BookLoanedUntil {
            get {
                return ResourceManager.GetString("BookLoanedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book was returned successfully.
        /// </summary>
        public static string BookReturned {
            get {
                return ResourceManager.GetString("BookReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed book items.
        /// </summary>
        public static string BorrowedBookItems {
            get {
                return ResourceManager.GetString("BorrowedBookItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed books.
        /// </summary>
        public static string BorrowedBooks {
            get {
                return ResourceManager.GetString("BorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed member.
        /// </summary>
        public static string BorrowedMember {
            get {
                return ResourceManager.GetString("BorrowedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reservation.
        /// </summary>
        public static string CancelReservation {
            get {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account status.
        /// </summary>
        public static string ChangeAccountStatus {
            get {
                return ResourceManager.GetString("ChangeAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account status for.
        /// </summary>
        public static string ChangeAccountStatusFor {
            get {
                return ResourceManager.GetString("ChangeAccountStatusFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create book.
        /// </summary>
        public static string CreateBook {
            get {
                return ResourceManager.GetString("CreateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create book item.
        /// </summary>
        public static string CreateBookItem {
            get {
                return ResourceManager.GetString("CreateBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create card.
        /// </summary>
        public static string CreateCard {
            get {
                return ResourceManager.GetString("CreateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create person.
        /// </summary>
        public static string CreatePerson {
            get {
                return ResourceManager.GetString("CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create rack.
        /// </summary>
        public static string CreateRack {
            get {
                return ResourceManager.GetString("CreateRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status is.
        /// </summary>
        public static string CurrentStatusIs {
            get {
                return ResourceManager.GetString("CurrentStatusIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book.
        /// </summary>
        public static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book item.
        /// </summary>
        public static string DeleteBookItem {
            get {
                return ResourceManager.GetString("DeleteBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rack.
        /// </summary>
        public static string DeleteRack {
            get {
                return ResourceManager.GetString("DeleteRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book.
        /// </summary>
        public static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book item.
        /// </summary>
        public static string EditBookItem {
            get {
                return ResourceManager.GetString("EditBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditPerson {
            get {
                return ResourceManager.GetString("EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rack.
        /// </summary>
        public static string EditRack {
            get {
                return ResourceManager.GetString("EditRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for member.
        /// </summary>
        public static string forMember {
            get {
                return ResourceManager.GetString("forMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lending.
        /// </summary>
        public static string Lending {
            get {
                return ResourceManager.GetString("Lending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lending menu.
        /// </summary>
        public static string LendingMenu {
            get {
                return ResourceManager.GetString("LendingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lending message.
        /// </summary>
        public static string LendingMessage {
            get {
                return ResourceManager.GetString("LendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian.
        /// </summary>
        public static string Librarian {
            get {
                return ResourceManager.GetString("Librarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian details.
        /// </summary>
        public static string LibrarianDetails {
            get {
                return ResourceManager.GetString("LibrarianDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member details.
        /// </summary>
        public static string MemberDetails {
            get {
                return ResourceManager.GetString("MemberDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other book items.
        /// </summary>
        public static string OtherBookItems {
            get {
                return ResourceManager.GetString("OtherBookItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay fine of.
        /// </summary>
        public static string PayFineOf {
            get {
                return ResourceManager.GetString("PayFineOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string PersonDetails {
            get {
                return ResourceManager.GetString("PersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        public static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks.
        /// </summary>
        public static string Racks {
            get {
                return ResourceManager.GetString("Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as librarian.
        /// </summary>
        public static string RegisterAsLibrarian {
            get {
                return ResourceManager.GetString("RegisterAsLibrarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as member.
        /// </summary>
        public static string RegisterAsMember {
            get {
                return ResourceManager.GetString("RegisterAsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve book item.
        /// </summary>
        public static string ReserveBookItem {
            get {
                return ResourceManager.GetString("ReserveBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved book items.
        /// </summary>
        public static string ReservedBookItems {
            get {
                return ResourceManager.GetString("ReservedBookItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved books.
        /// </summary>
        public static string ReservedBooks {
            get {
                return ResourceManager.GetString("ReservedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved member.
        /// </summary>
        public static string ReservedMember {
            get {
                return ResourceManager.GetString("ReservedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan book barcode.
        /// </summary>
        public static string ScanBookBarcode {
            get {
                return ResourceManager.GetString("ScanBookBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan library card barcode.
        /// </summary>
        public static string ScanLibraryCardBarcode {
            get {
                return ResourceManager.GetString("ScanLibraryCardBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process is irreversible.
        /// </summary>
        public static string ThisProcessIsIreverrsible {
            get {
                return ResourceManager.GetString("ThisProcessIsIreverrsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to continue.
        /// </summary>
        public static string toContinue {
            get {
                return ResourceManager.GetString("toContinue", resourceCulture);
            }
        }
    }
}
